### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by ThatDex** [ThatDex/dex-cogs#11]
- [ ] Figure out user input
- [ ] Output message to notify admin to authorize application on browser (In Discord)
- [ ] Add Event modification
- [ ] Add Event add/remove
- [ ] Add Event Search
- [x] Limit maxResults ( #171 )
- [x] Calc max output for format options
- [x] def common code ( #152 )
- [x] Add List events custom range ( #84 )
- [x] Add List events this and next week ( #79 )
- [x] Figure out help ( #58 )
- [x] Make it all sub-commands ( #56 )
- [x] Re-write varibles to work from settings.json (cal_id) ( #32 )
- [x] Add support for multiple calendars ( #28 )
  - [x] Create command to list available calendars and what call to use to search them
  - [x] Modify commands to input what calendar they want searched (Maybe a switch or by-command input)
- [x] Format output to be a single code block ( #14 )
- [x] Add Today's Agenda command ( #13 )
- [x] Get the basics working ( #10 )
- [x] Learn to spell ( #8 )
